version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    working_dir: /app/apps/server
    command: node dist/main.js
    volumes:
      - .:/app
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app/apps/client
    command: npm run start
    volumes:
      - .:/app
    restart: unless-stopped